[package]
name = "extract_words"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scraper = "0.17.1"
serde = "1.0.171"
serde_json = "1.0.103"

